version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka0: &broker-default
    # https://docs.confluent.io/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility
    image: confluentinc/cp-kafka:6.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment: &default-broker-env
      KAFKA_BROKER_ID: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka0:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka0:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka1:
    <<: *broker-default
    ports:
      - "9093:9093"
    environment:
      <<: *default-broker-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "INTERNAL://kafka1:29093,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29093,EXTERNAL://localhost:9093"
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:6.0.0
    depends_on:
      - kafka0
      - kafka1
      - nginx
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka0:29092,kafka1:29093
      KAFKA_REST_HOST_NAME: the-proxy-url
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
  kafka-cli:
    depends_on:
      - kafka0
      - kafka1
    image: frser/kafka-cli:2.6.0
    volumes:
      - ./produce_messages_via_cli.sh:/app/produce_messages_via_cli.sh
    environment:
      BOOTSTRAP_SERVER: kafka0:29092
      CREATE_TOPICS: >-
        test.telemetry.readings:2:1,
        test.telemetry.alarms:2:1,
  nginx:
    build:
      context: nginx_proxy
    ports:
      - 8080:8080
      - 8082:8082
    environment:
        TDA_READINGS_TOPIC: test.telemetry.readings
        TDA_ERRORS_TOPIC: test.telemetry.alarms
